### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.Tracing.EventSourceSettings
  id: EventSourceSettings
  children:
  - System.Diagnostics.Tracing.EventSourceSettings.Default
  - System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  langs:
  - csharp
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
  type: Enum
  summary: To be added.
  remarks: To be added.
  syntax:
    content: >-
      [System.Flags]

      public enum EventSourceSettings
  inheritance:
  - System.Object
  - System.ValueType
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  id: Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: Default
  nameWithType: EventSourceSettings.Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: To be added.
  syntax:
    content: Default
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  id: EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: EtwManifestEventFormat
  nameWithType: EventSourceSettings.EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: To be added.
  syntax:
    content: EtwManifestEventFormat
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  id: EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: EtwSelfDescribingEventFormat
  nameWithType: EventSourceSettings.EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: To be added.
  syntax:
    content: EtwSelfDescribingEventFormat
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  id: ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  name: ThrowOnEventWriteErrors
  nameWithType: EventSourceSettings.ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Tracing
  summary: To be added.
  syntax:
    content: ThrowOnEventWriteErrors
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
      description: To be added.
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: Default
  nameWithType: EventSourceSettings.Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: EtwManifestEventFormat
  nameWithType: EventSourceSettings.EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: EtwSelfDescribingEventFormat
  nameWithType: EventSourceSettings.EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  isExternal: false
  name: ThrowOnEventWriteErrors
  nameWithType: EventSourceSettings.ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
- uid: System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
